"""Document integrity / tamper detection.

Honest tiering:
  - STRONG: provenance metadata. A genuine certificate is scanned/issued; a fake is
    *designed*. PDFs/images carry the tool that made them (Canva, CorelDRAW, Photoshop…),
    and a real photo carries camera metadata. These are reliable, cheap signals.
  - WEAK: pixel forensics (ELA). Catches some photo-splicing; fails on fresh fakes and
    false-positives on innocent re-saves. Clearly labeled as a hint, never proof.

Neither replaces matching the issuer's record — a flawless fake with scrubbed metadata
is only caught by verification. But this flags the lazy majority, with no GPU or key.
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field

DESIGN_TOOLS = [
    "canva", "coreldraw", "corel", "photoshop", "illustrator", "indesign", "inkscape",
    "gimp", "microsoft word", "word for", "powerpoint", "figma", "affinity", "pixlr",
    "paint.net", "snagit", "acrobat",
]

# Tokens that, in metadata, indicate AI generation. Specific on purpose (no bare "ai")
# to avoid false matches in common words. Strong WHEN PRESENT, but strippable.
AI_TOOLS = [
    "dall·e", "dall-e", "dalle", "openai", "gpt-4", "gpt-image", "midjourney",
    "stable diffusion", "stablediffusion", "stability ai", "adobe firefly", "firefly",
    "imagen", "leonardo.ai", "ideogram", "synthid", "generative ai", "made with ai",
    "google ai", "flux.1",
]

# Markers that an embedded C2PA / Content-Credentials provenance manifest is present.
C2PA_MARKERS = (b"c2pa", b"jumbf", b"contentcred", b"content credentials")


@dataclass
class IntegritySignal:
    check: str
    severity: str            # info | warning | error
    detail: str


@dataclass
class IntegrityReport:
    risk: str                # low | medium | high
    file_kind: str           # pdf | image
    software: str | None
    signals: list[IntegritySignal] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "risk": self.risk,
            "file_kind": self.file_kind,
            "software": self.software,
            "signals": [{"check": s.check, "severity": s.severity, "detail": s.detail} for s in self.signals],
        }


def _match_tool(text: str | None) -> str | None:
    low = (text or "").lower()
    return text if any(name in low for name in DESIGN_TOOLS) else None


def _match_ai(text: str | None) -> str | None:
    low = (text or "").lower()
    return text if any(name in low for name in AI_TOOLS) else None


def _c2pa_present(data: bytes) -> bool:
    low = data.lower()
    return any(m in low for m in C2PA_MARKERS)


def _risk(signals: list[IntegritySignal]) -> str:
    if any(s.severity == "error" for s in signals):
        return "high"
    if any(s.severity == "warning" for s in signals):
        return "medium"
    return "low"


def analyze(file_bytes: bytes, filename: str = "") -> IntegrityReport:
    is_pdf = file_bytes[:5] == b"%PDF-" or filename.lower().endswith(".pdf")
    return _analyze_pdf(file_bytes) if is_pdf else _analyze_image(file_bytes, filename)


def _analyze_pdf(data: bytes) -> IntegrityReport:
    import fitz

    signals: list[IntegritySignal] = []
    software = None
    try:
        doc = fitz.open(stream=data, filetype="pdf")
    except Exception as exc:
        return IntegrityReport("medium", "pdf", None, [IntegritySignal("parse", "warning", f"could not parse PDF: {exc}")])

    meta = doc.metadata or {}
    producer, creator = meta.get("producer") or "", meta.get("creator") or ""
    tool = _match_tool(producer) or _match_tool(creator)
    if tool:
        software = tool
        signals.append(IntegritySignal(
            "design_tool", "error",
            f"PDF was created/edited with a design tool ({tool}) — issued certificates are "
            f"scanned or generated by the issuer, not designed in such tools",
        ))
    elif producer or creator:
        software = producer or creator
        signals.append(IntegritySignal("producer", "info", f"PDF producer/creator: {software}"))

    revisions = data.count(b"%%EOF")
    if revisions > 1:
        signals.append(IntegritySignal(
            "revisions", "warning",
            f"PDF contains {revisions} revisions — it was edited/updated after the original was created",
        ))

    try:
        page = doc[0]
        if page.get_text().strip() and not page.get_images():
            signals.append(IntegritySignal(
                "born_digital", "info",
                "page is born-digital text, not a scan (expected for some e-certificates)",
            ))
    except Exception:
        pass
    doc.close()
    return IntegrityReport(_risk(signals), "pdf", software, signals)


def _analyze_image(data: bytes, filename: str) -> IntegrityReport:
    from PIL import ExifTags, Image

    signals: list[IntegritySignal] = []
    software = None
    try:
        img = Image.open(io.BytesIO(data))
    except Exception as exc:
        return IntegrityReport("medium", "image", None, [IntegritySignal("parse", "warning", f"could not parse image: {exc}")])

    exif: dict = {}
    try:
        exif = {ExifTags.TAGS.get(k, k): v for k, v in img.getexif().items()}
    except Exception:
        pass

    sw = exif.get("Software")
    if sw and _match_tool(str(sw)):
        software = str(sw)
        signals.append(IntegritySignal(
            "design_tool", "error",
            f"image was last saved by an editor ({sw}) — not a straight camera/scanner output",
        ))
    elif sw:
        software = str(sw)
        signals.append(IntegritySignal("software", "warning", f"image carries a Software tag: {sw}"))

    make, model = exif.get("Make"), exif.get("Model")
    if make or model:
        signals.append(IntegritySignal("camera", "info", f"camera metadata present: {make or ''} {model or ''}".strip()))
    else:
        signals.append(IntegritySignal(
            "no_camera", "warning",
            "no camera make/model in metadata — the image was likely exported from software "
            "rather than photographed or scanned",
        ))

    try:
        score = _ela_score(img)
        if score is not None and score >= 0.18:
            signals.append(IntegritySignal(
                "ela", "info",
                f"error-level analysis hints at possible localized edits (score {score:.2f}) — "
                f"weak signal, verify manually",
            ))
    except Exception:
        pass

    return IntegrityReport(_risk(signals), "image", software, signals)


def _ela_score(img) -> float | None:
    """Very rough error-level analysis: max re-compression delta, normalized 0..1. Weak by design."""
    from PIL import Image, ImageChops

    rgb = img.convert("RGB")
    buf = io.BytesIO()
    rgb.save(buf, "JPEG", quality=90)
    buf.seek(0)
    diff = ImageChops.difference(rgb, Image.open(buf))
    extrema = diff.getextrema()  # ((min,max), (min,max), (min,max))
    max_delta = max(hi for _, hi in extrema)
    return max_delta / 255.0
